language: php

matrix:
    include:
        - php: 7.3
          env: LARAVEL_VERSION=8.0
        - php: 7.3
          env: LARAVEL_VERSION=7.0
        - php: 7.2
          env: LARAVEL_VERSION=6.0

script:
    - ./tests/init-${LARAVEL_VERSION}.sh && vendor/bin/phpunit

after_success:
    - travis_retry php vendor/bin/php-coveralls