language: php

matrix:
    include:
        - php: 7.1.3
          env: LARAVEL_VERSION=5.6
        - php: 7.0
          env: LARAVEL_VERSION=5.5

script:
    - ./tests/init-${LARAVEL_VERSION}.sh && vendor/bin/phpunit
