language: php

matrix:
    include:
    	  - php: 7.1.3
          env: LARAVEL_VERSION=5.7
        - php: 7.1.3
          env: LARAVEL_VERSION=5.6
        - php: 7.0
          env: LARAVEL_VERSION=5.5
        - php: 7.0
          env: LARAVEL_VERSION=5.4

script:
    - ./tests/init-${LARAVEL_VERSION}.sh && vendor/bin/phpunit

after_success:
    - travis_retry php vendor/bin/php-coveralls